// Code generated by "stringer -type=Choice,Outcome -output enums_string.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Rock-0]
	_ = x[Paper-1]
	_ = x[Scissors-2]
}

const _Choice_name = "RockPaperScissors"

var _Choice_index = [...]uint8{0, 4, 9, 17}

func (i Choice) String() string {
	if i < 0 || i >= Choice(len(_Choice_index)-1) {
		return "Choice(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Choice_name[_Choice_index[i]:_Choice_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Win-0]
	_ = x[Tie-1]
	_ = x[Lose-2]
}

const _Outcome_name = "WinTieLose"

var _Outcome_index = [...]uint8{0, 3, 6, 10}

func (i Outcome) String() string {
	if i < 0 || i >= Outcome(len(_Outcome_index)-1) {
		return "Outcome(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Outcome_name[_Outcome_index[i]:_Outcome_index[i+1]]
}
